### ISSUE TITLE
Use of command aliases

### ISSUE THREAD

**Issue by lafrenierejm** [TSYS-Merchant/posh-svn#11]
[PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer), an official Microsoft project, [throws warnings](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Rules/AvoidAlias.cs) over the use of Cmdlet aliases.

Would there be any objections to a pull request to change all aliases to their full Cmdlets?

**Comment by ghost** [comment]
No objections at all! Please submit and we'll merge.

**Comment by lafrenierejm** [comment]
Great! I will plan to do so within the next few days.

Is there a recommended way to test for regressions?  This change will be simple enough that I'm not anticipating any, but I would prefer to be safe.

**Comment by withinfocus** [comment]
No recommendations there -- the extension is relatively simple to exercising its few commands will likely be sufficient.

**Comment by withinfocus** [comment]
Resolved by #13.
