### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by lafrenierejm** [TSYS-Merchant/posh-svn#12]
Is there a canonical style guideline for this repo?  I have not had luck in discovering what it may just by looking at the files themselves.

**Comment by ghost** [comment]
Definitely not. This was built some time ago and hasn't changed a lot for a number of years; we picked it up to get some mandatory changes in place. We are open to any sort of standardization.

**Comment by lafrenierejm** [comment]
Sounds good. I'll search around for any standards or at least examples and post what I find.

**Comment by lafrenierejm** [comment]
Microsoft has a canonical list of [cmdlet development guidelines](https://msdn.microsoft.com/en-us/library/ms714657%28v=vs.85%29.aspx);  I suggest that we strive to follow all of them.

[PoshCode's PowerShellPracticeAndStyle](https://github.com/PoshCode/PowerShellPracticeAndStyle) is a compilation of best practices as arrived at by the community.  It appears to be quite thorough, and adherence to it would certainly help in providing well-document consistency.

Microsoft's open source [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) may also be a valuable resource.
