### ISSUE TITLE
Module has no apparent effect

### ISSUE THREAD

**Issue by Artfunkel** [TSYS-Merchant/posh-svn#15]
I ran `Install-Module posh-svn`, openend a new PowerShell window in my repo and...nothing happened.

I manually incorporated `profile.example.ps1` into my profile and...nothing happened.

The only thing I can make work is the `Get-SvnStatus` cmdlet, which returns a table of values. There's no command prompt decoration like my experience with posh-git led me to expect.

What am I missing?

**Comment by Artfunkel** [comment]
Forgot to mention that calling the `prompt` function in the profile example errors because `Write-VcsStatus` isn't recognised.

**Comment by cdonnellytx** [comment]
@Artfunkel I've noticed that, at least on my machine, posh-svn won't load anything unless posh-git is also imported.

My guess is that you'll probably have to install/import posh-git as well.

If you really want posh-svn but not posh-git, you'll probably need to convince posh-git's maintainers to split out the generic VCS-in-prompt functionality into a separate module both it and posh-git depend on.  Given git's relative popularity to other VCS solutions, that may or may not be feasible...

**Comment by withinfocus** [comment]
Significant upgrades to the project have occurred at this point and we don't believe any dependencies exist. Closing out.
