### ISSUE TITLE
How may I install and use it?

### ISSUE THREAD

**Issue by RafaelGorski** [TSYS-Merchant/posh-svn#9]
Hi,

How may I install and use it?
I saw the psget tool, however how can I install it manually direct to powershell?
What is the expected functionalities?

//Rafael

**Comment by ghost** [comment]
http://psget.net/directory/posh-svn/

**Comment by lafrenierejm** [comment]
Could this information that go in a readme?

**Comment by ghost** [comment]
Here you go: 5accb5f9ab81f2131e4fa1044edd87f99fefdc17
